version: 2
updates:
- package-ecosystem: npm
  directory: "/server"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: tailwindcss
    versions:
    - 2.0.4
  - dependency-name: xmldom
    versions:
    - 0.5.0
  - dependency-name: postcss
    versions:
    - 8.2.6
    - 8.2.7
    - 8.2.8
  - dependency-name: pug
    versions:
    - 3.0.2
  - dependency-name: autoprefixer
    versions:
    - 10.2.3
    - 10.2.4
    - 10.2.5
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: express-validator
    versions:
    - 6.10.0
    - 6.9.2
  - dependency-name: pm2
    versions:
    - 4.5.2
    - 4.5.5
  - dependency-name: "@fullhuman/postcss-purgecss"
    versions:
    - 4.0.0
    - 4.0.2
  - dependency-name: connect-redis
    versions:
    - 5.1.0
  - dependency-name: fastest-validator
    versions:
    - 1.10.0
  - dependency-name: node-schedule
    versions:
    - 1.3.3
    - 2.0.0
  - dependency-name: helmet
    versions:
    - 4.4.1
  - dependency-name: "@types/express"
    versions:
    - 4.17.11
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: vite-plugin-windicss
    versions:
    - 0.13.1
    - 0.14.0
    - 0.14.6
    - 0.15.2
  - dependency-name: vite
    versions:
    - 2.1.5
    - 2.2.1
  - dependency-name: vue-tsc
    versions:
    - 0.0.18
    - 0.0.20
    - 0.0.21
    - 0.0.23
    - 0.0.24
  - dependency-name: "@vue/compiler-sfc"
    versions:
    - 3.0.10
    - 3.0.11
  - dependency-name: vue
    versions:
    - 3.0.10
    - 3.0.11
  - dependency-name: "@vitejs/plugin-vue"
    versions:
    - 1.2.0
    - 1.2.1
